/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatBar: typeof import('./src/components/ChatBar.vue')['default']
    MasonryLayout: typeof import('./src/components/MasonryLayout.vue')['default']
    MiddlePage: typeof import('./src/views/MiddlePage.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
  }
}
